
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.MessageFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class TransactionDetail extends javax.swing.JFrame {

    DefaultTableModel dm;
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form TransactionDetail
     */
    public TransactionDetail() {
        super(" Transaction Detail");
        initComponents();
        conn = javaconnect.getConnection();
//        bank();
        clock();
    }

    //search engine
    private void filter(String query) {
        dm = (DefaultTableModel) table1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
        table1.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    public void fetch() {
        try {
            JTableHeader header = table1.getTableHeader();
            header.setForeground(Color.red);
            header.setFont(new Font("Tahome", Font.ITALIC, 12));
            table1.setRowSelectionInterval(0, 0);
            int iii = table1.getSelectedRow();
//        JOptionPane.showMessageDialog(null,iii);
            dm = (DefaultTableModel) table1.getModel();
            String name = dm.getValueAt(iii, 1).toString();
            String accno = dm.getValueAt(iii, 2).toString();
            String q = "select id as Id,bank_name as 'Bank Name',bank_ac_no as 'Acc No',transaction_type as 'Transaction Type',amount as 'Amount',date as 'Date' from bank_transaction where bank_name = '" + name + "' and bank_ac_no = '" + accno + "' ORDER BY id DESC";
//            String q = "select item_date as Receiving_Date from item ORDER BY id DESC";
            pst = conn.prepareStatement(q);
            rs = pst.executeQuery();
            table1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {

        }
    }

    public void clock() {
        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        date.setText(year + "-" + (month + 1) + "-" + day);
    }

    public void getsum() {
        int rowsCount = table1.getRowCount();
        Double sum = 0.0;
//        Double sum1 = 0.0;
//        Double sum2 = 0.0;
        for (int i = 0; i < rowsCount; i++) {
            sum = sum + Double.parseDouble(table1.getValueAt(i, 4).toString());
//                sum1 = sum1 + Double.parseDouble(table1.getValueAt(i,11).toString());                
        }
        if (search_text1.getText() == "Deposit") {
            deposit.setText(Double.toString(sum));
        } else if (search_text1.getText() == "Withdraw") {
            withdraw.setText(Double.toString(sum));
        } else {
            interest.setText(Double.toString(sum));
        }
//        jLabel6.setText(Double.toString(sum1));
//        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        search_text1 = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        deposit = new javax.swing.JLabel();
        withdraw = new javax.swing.JLabel();
        interest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        jLabel1.setText("Transaction Detail");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 160, -1));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 80, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Search");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 90, -1));

        search_text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                search_text1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_text1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_text1KeyTyped(evt);
            }
        });
        jPanel1.add(search_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 190, -1));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 120, -1));

        table1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table1.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Bank Name", "Acc No", "Transaction Type", "Amount", "Date"
            }
        ));
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        deposit.setFont(new java.awt.Font("Sitka Heading", 3, 12)); // NOI18N

        withdraw.setFont(new java.awt.Font("Sitka Heading", 3, 12)); // NOI18N

        interest.setFont(new java.awt.Font("Sitka Heading", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(502, 502, 502)
                .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(interest, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1079, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        if (search_text1.getText() == "D"|| search_text1.getText() == "De" || search_text1.getText() == "Dep" || search_text1.getText() == "Depo" || search_text1.getText() == "Depos" || search_text1.getText() == "Deposi" || search_text1.getText() == "Deposit") {
            MessageFormat footer = new MessageFormat("Deposit: '" + deposit.getText() + "'");
            try {
                table1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            } catch (java.awt.print.PrinterException e) {
                System.err.format("cannot print", e.getMessage());
            }
        } else if (search_text1.getText() == "W" || search_text1.getText() == "Wi" || search_text1.getText() == "Wit"  || search_text1.getText() == "With" || search_text1.getText() == "Withd" || search_text1.getText() == "Withdr" || search_text1.getText() == "Withdra" || search_text1.getText() == "Withdraw") {
            MessageFormat footer = new MessageFormat("Withdraw: '" + withdraw.getText() + "'");
            try {
                table1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            } catch (java.awt.print.PrinterException e) {
                System.err.format("cannot print", e.getMessage());
            }
        } else if(interest.getText() == "I" || interest.getText() == "In" || interest.getText() == "Int"  || interest.getText() == "Inte" || interest.getText() == "Inter" || interest.getText() == "Intere" || interest.getText() == "Interes" || interest.getText() == "Interest") {
            MessageFormat footer = new MessageFormat("Interest: '" + interest.getText() + "");
            try {
                table1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
            } catch (java.awt.print.PrinterException e) {
                System.err.format("cannot print", e.getMessage());
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fetch();
    }//GEN-LAST:event_formWindowOpened

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table1MouseClicked

    private void search_text1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_text1KeyPressed
        // TODO add your handling code here:              
    }//GEN-LAST:event_search_text1KeyPressed

    private void search_text1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_text1KeyReleased
        // TODO add your handling code here:
        String query = search_text1.getText();
        filter(query);
        getsum();
    }//GEN-LAST:event_search_text1KeyReleased

    private void search_text1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_text1KeyTyped
        // TODO add your handling code here:        
    }//GEN-LAST:event_search_text1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JLabel deposit;
    private javax.swing.JLabel interest;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search_text1;
    public javax.swing.JTable table1;
    private javax.swing.JLabel withdraw;
    // End of variables declaration//GEN-END:variables
}
